### ISSUE TITLE
Fatal error: Uncaught exception 'RuntimeException' 

### ISSUE THREAD

**Issue by patfee** [ThatCasualMatt/Nest-Extended#5]
Hi,
i receive an error as follows:
Fatal error: Uncaught exception 'RuntimeException' with message 'Error: HTTP request to https://home.nest.com/user/login returned an error: error setting certificate verify locations: CAfile: /var/services/tmp/cacert.pem CApath: none' in /volume1/web/nest/resources/libs/nest/nest.class.php:690 Stack trace: #0 /volume1/web/nest/resources/libs/nest/nest.class.php(622): Nest->doRequest('POST', 'https://home.ne...', Array) #1 /volume1/web/nest/resources/libs/nest/nest.class.php(573): Nest->doPOST('https://home.ne...', Array) #2 /volume1/web/nest/resources/libs/nest/nest.class.php(99): Nest->login() #3 /volume1/web/nest/resources/utils/nest-get-data.php(20): Nest->__construct() #4 {main} thrown in /volume1/web/nest/resources/libs/nest/nest.class.php on line 690

it is the first time installation on my synology nas

nothing is inserted in the database too

thanks for your assistance

**Comment by norbital** [comment]
Mine has been running for months... Suddenly today I'm getting the same error and no data being added to my database.

**Comment by norbital** [comment]
Actually... Figured it out... Nest API update... need to update the nest.class.php form the unofficial nest API github page... and drop it in \resources\libs\nest\ folder

I fixed it a while back twice.. forgot to update here.
