### ISSUE TITLE
Multiple Nests - Specify which data to collect

### ISSUE THREAD

**Issue by jase31** [ThatCasualMatt/Nest-Extended#8]
Can anyone give any more info how to specify which thermostat to read the data from. the script is working however it is reading only from the first nest. How can I read the data from the second nest?

**Comment by falvesjr** [comment]
I would also appreciate more info on how to get multiple Nests to work with this. I have two Nests, but can only get data from one, which I suppose is the "first one" on my Nest account. I saw something elsewhere about using each Nest's serial number to address them individually, so it might be helpful here. 

Maybe this can be implemented by either having multiple sets of lines (solid, dashed, etc) or by having a selection popup that would let you choose which Nest to look at individually. I don't think the multiple lines option would work very well, especially if one has more than two Nests, so the individual display is probably a better idea.

Matt, are you still interested in this project? Maybe you can chime in! =)

**Comment by mclemens68** [comment]
Anyone ever figure this one out?

I've also got the scripts working, but would be nice to be able to tweak things to be able to see both my nests.

**Comment by Toehead** [comment]
This uses the unoffical nest API listed. 

In the examples, it covers how to pull device info from multiple devices. https://github.com/gboudreau/nest-api/blob/master/examples.php

You would need to edit the get-data command to pull from multiple devices and create multiple databases.

**Comment by zevlag** [comment]
I also would love for multiple nests to be supported
